### ISSUE TITLE
VN: replace fob_box by VN one instead of default

### ISSUE THREAD

**Issue by SunStalker** [SunStalker/KP-Liberation#9]
currently: FOB_box_typename = "B_Slingload_01_Cargo_F";                            // This is the FOB as a container. (Land_vn_cargo20_military_green_f could be usable when it is slingloadable.

Land_vn_cargo20_military_green_f 

https://wiki.sogpf.com/index.php/CfgVehicles_EMPTY shows it is NOT slingloadable, but 137 items across all VN factions are.
![image](https://github.com/SunStalker/KP-Liberation/assets/32316712/b338b9df-dfc0-46e8-bf84-03ce2aee0f3b)

vn_us_komex_medium_02 is best one, if not even the small version

**Comment by FatRefrigerator** [comment]
These are great options, I like the other suggestions like the mobile respawn and the flight radar.

My big issue with it is that if I were to update the workshop version with those new things, anyone currently playing that has one of those things deployed will have them disappear. That's what happens when you update the preset with new classnames unfortunately.
